version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5485:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_motion:/var/lib/postgresql/data

  backend:
    image: discovery:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: "python manage.py runserver 0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    tty: true





volumes:
  postgres_motion:
